### PR TITLE
Fixing recaptcha block on animeout with Rest API

### PR DESCRIPTION
**Pull request by ctrlji**

### CODE REVIEW

**Comment by LordGhostX** [comment]
Thank you very much for this PR, really appreciated.

**Comment by ctrlji** [comment]
Its a pleasure boss, I did a more thorough testing and review on what we have now, downloading multiple anime videos from the host site from the different streams available. And I noticed that few lines of codes needs to be corrected for a much reliable code base. kindly checkout the new pull request. Thanks.

**Comment by Mastersam07** [comment]
The person that opened this PR and the person that merged it, God bless you.

**Comment by ctrlji** [comment]
> The person that opened this PR and the person that merged it, God bless you.

Thanks!

**Pull request merged**
